version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: englishdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "3000:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"